// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5VzljaRi5JOauSWHHj8QovRs6O6bswIU',
    appId: '1:285949629036:web:ac1f2b8a1c38a81bf8be49',
    messagingSenderId: '285949629036',
    projectId: 'bloodfy-dc1f2',
    authDomain: 'bloodfy-dc1f2.firebaseapp.com',
    storageBucket: 'bloodfy-dc1f2.appspot.com',
    measurementId: 'G-6RQCFNEP6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmMCXi6bLvGeo84046fMppv4SNV5pDft8',
    appId: '1:285949629036:android:922db807d3376324f8be49',
    messagingSenderId: '285949629036',
    projectId: 'bloodfy-dc1f2',
    storageBucket: 'bloodfy-dc1f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcua2x5Bf1wqYRb55Si6b0elwfsIy3iys',
    appId: '1:285949629036:ios:952beb6217309ab8f8be49',
    messagingSenderId: '285949629036',
    projectId: 'bloodfy-dc1f2',
    storageBucket: 'bloodfy-dc1f2.appspot.com',
    iosClientId: '285949629036-8qgcspafi2isgen3ehml9a181fsa7t8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodfy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcua2x5Bf1wqYRb55Si6b0elwfsIy3iys',
    appId: '1:285949629036:ios:952beb6217309ab8f8be49',
    messagingSenderId: '285949629036',
    projectId: 'bloodfy-dc1f2',
    storageBucket: 'bloodfy-dc1f2.appspot.com',
    iosClientId: '285949629036-8qgcspafi2isgen3ehml9a181fsa7t8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodfy',
  );
}
